version: "3.9"

services:
    grpc-service:
        build: ../..
        ports:
            - "9090:9090"
            - "8080:8080"
        environment:
            APP_ENV: production
            GRPC_PORT: 9090
            HTTP_PORT: 8080
