title: {{cookiecutter.project_name}}
author: {{cookiecutter.author_name}}
copyright: "{{cookiecutter.author_name}}"
logo: _static/logo.png

only_build_toc_files: true

repository:
  url: https://github.com/{{cookiecutter.project_slug}}
  path_to_book: docs

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  
execute:
  execute_notebooks: "off"

sphinx:
  config:
    html_theme_options:
      repository_url: https://github.com/{{cookiecutter.project_slug}}
      use_repository_button: true
